apiVersion: v2
name: benxiao-console
description: a net cloud service based on MinIO
version: "{{.Version}}"
maintainers:
  - name: kinson
    email: mail.kinson.liu@gmail.com
    url: www.kinson.fun
sources:
  - https://github.com/benxiao-app/benxiao-console